# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# coding: utf-8
#
# LargeCategorie.create(name: 'レディース', sort_by: 1)
# LargeCategorie.create(name: 'メンズ', sort_by: 2)
# LargeCategorie.create(name: 'ベビー・キッズ', sort_by: 3)
# LargeCategorie.create(name: 'インテリア・住まい・小物', sort_by: 4)
# LargeCategorie.create(name: '本・音楽・ゲーム', sort_by: 5)
# LargeCategorie.create(name: 'おもちゃ・ホビー・グッズ', sort_by: 6)
# LargeCategorie.create(name: 'コスメ・香水・美容', sort_by: 7)
# LargeCategorie.create(name: '家電・スマホ・カメラ', sort_by: 8)
# LargeCategorie.create(name: 'スポーツ・レジャー', sort_by: 9)
# LargeCategorie.create(name: 'ハンドメイド', sort_by: 10)
# LargeCategorie.create(name: 'チケット', sort_by: 11)
# LargeCategorie.create(name: '自動車・オートバイ', sort_by: 12)
# LargeCategorie.create(name: 'その他', sort_by: 13)
# #
# MiddleCategorie.create(name: 'トップス', sort_by: 14)
# MiddleCategorie.create(name: 'ジャケット/アウター', sort_by: 15)
# MiddleCategorie.create(name: 'パンツ', sort_by: 16)
# MiddleCategorie.create(name: 'スカート', sort_by: 17)
# MiddleCategorie.create(name: 'ワンピース', sort_by: 18)
# MiddleCategorie.create(name: '靴', sort_by: 19)
# MiddleCategorie.create(name: 'ルームウェア/パジャマ', sort_by: 20)
# MiddleCategorie.create(name: 'レッグウェア', sort_by: 21)
# MiddleCategorie.create(name: '帽子', sort_by: 22)
# MiddleCategorie.create(name: 'バッグ', sort_by: 23)
# MiddleCategorie.create(name: 'アクセサリー', sort_by: 24)
# MiddleCategorie.create(name: 'ヘアアクセサリー', sort_by: 25)
# MiddleCategorie.create(name: '小物', sort_by: 26)
# MiddleCategorie.create(name: '時計', sort_by: 27)
# MiddleCategorie.create(name: 'ウィッグ/エクステ', sort_by: 28)
# MiddleCategorie.create(name: '浴衣/水着', sort_by: 29)
# MiddleCategorie.create(name: 'スーツ/フォーマル/ドレス', sort_by: 30)
# MiddleCategorie.create(name: 'マタニティ', sort_by: 31)
# MiddleCategorie.create(name: 'その他', sort_by: 32)
#
# SmallCategorie.create(name: 'Tシャツ/カットソー(半袖/袖なし)',  sort_by: 1)
# SmallCategorie.create(name: 'Tシャツ/カットソー(七分/長袖)',  sort_by: 2)
# SmallCategorie.create(name: 'シャツ/ブラウス(半袖/袖なし)',  sort_by: 3)
# SmallCategorie.create(name: 'シャツ/ブラウス(七分/長袖)',  sort_by: 4)
# SmallCategorie.create(name: 'ポロシャツ',  sort_by: 5)
# SmallCategorie.create(name: 'キャミソール',  sort_by: 6)
# SmallCategorie.create(name: 'タンクトップ',  sort_by: 7)
# SmallCategorie.create(name: 'ホルターネック',  sort_by: 8)
# SmallCategorie.create(name: 'ニット/セーター',  sort_by: 9)
# SmallCategorie.create(name: 'チュニック',  sort_by: 10)
# SmallCategorie.create(name: 'カーディガン/ボレロ',  sort_by: 11)
# SmallCategorie.create(name: 'アンサンブル',  sort_by: 12)
# SmallCategorie.create(name: 'ベスト/ジレ',  sort_by: 13)
# SmallCategorie.create(name: 'パーカー',  sort_by: 14)
# SmallCategorie.create(name: 'トレーナー/スウェット',  sort_by: 15)
# SmallCategorie.create(name: 'ベアトップ/チューブトップ',  sort_by: 16)
# SmallCategorie.create(name: 'ジャージ',  sort_by: 17)
# SmallCategorie.create(name: 'その他',  sort_by: 18)
#
# SizeKind.create(name: '服')
# #
# Size.create(name: 'XXS以下', sort_by: 1, size_kind_id: 1)
# Size.create(name: 'XS(SS)', sort_by: 2, size_kind_id: 1)
# Size.create(name: 'S', sort_by: 3, size_kind_id: 1)
# Size.create(name: 'M', sort_by: 4, size_kind_id: 1)
# Size.create(name: 'L', sort_by: 5, size_kind_id: 1)
# Size.create(name: 'XL(LL)', sort_by: 6, size_kind_id: 1)
# Size.create(name: '2XL(3L)', sort_by: 7, size_kind_id: 1)
# Size.create(name: '3XL(4L)', sort_by: 8, size_kind_id: 1)
# Size.create(name: '4XL(5L)以上', sort_by: 9, size_kind_id: 1)
# Size.create(name: 'FREE SIZE', sort_by: 10, size_kind_id: 1)
# #
# Condition.create(name: '新品、未使用', sort_by: 1)
# Condition.create(name: '未使用に近い', sort_by: 2)
# Condition.create(name: '目立った傷や汚れなし', sort_by: 3)
# Condition.create(name: 'やや傷や汚れあり', sort_by: 4)
# Condition.create(name: '傷や汚れあり', sort_by: 5)
# Condition.create(name: '全体的に状態が悪い', sort_by: 6)
#
# DeliveryFeePay.create(name: '着払い(購入者負担)', sort_by: 2)
# DeliveryFeePay.create(name: '送料込み(出品者負担)', sort_by: 1)
# #
# DeliveryMethod.create(name: '未定', sort_by: 1)
# DeliveryMethod.create(name: 'ゆうメール', sort_by: 3)
# DeliveryMethod.create(name: 'ゆうパケット', sort_by: 9)
# DeliveryMethod.create(name: 'レターパック', sort_by: 4)
# DeliveryMethod.create(name: '普通郵便(定形、定形外)', sort_by: 5)
# DeliveryMethod.create(name: 'クロネコヤマト', sort_by: 6)
# DeliveryMethod.create(name: 'ゆうパック', sort_by: 7)
# DeliveryMethod.create(name: 'クリックポスト', sort_by: 8)
# DeliveryMethod.create(name: 'らくらくメルカリ便', sort_by: 2)
#
# Prefecture.create(name: '北海道')
# Prefecture.create(name: '青森県')
# Prefecture.create(name: '岩手県')
# Prefecture.create(name: '宮城県')
# Prefecture.create(name: '秋田県')
# Prefecture.create(name: '山形県')
# Prefecture.create(name: '福島県')
# Prefecture.create(name: '茨城県')
# Prefecture.create(name: '栃木県')
# Prefecture.create(name: '群馬県')
# Prefecture.create(name: '埼玉県')
# Prefecture.create(name: '千葉県')
# Prefecture.create(name: '東京都')
# Prefecture.create(name: '神奈川県')
# Prefecture.create(name: '新潟県')

# ShipmentPeriod.create(name: '1~2日で発送', sort_by: 1)
# ShipmentPeriod.create(name: '2~3日で発送', sort_by: 2)
# ShipmentPeriod.create(name: '4~7日で発送', sort_by: 3)
#
# User.create(nickname: 'テスト', email: 'test@test.com', password: 'passw0rd')
# User.create(nickname: 'テスト2', email: 'test2@test.com', password: 'passw0rd')
#
#
# http://ab-st.net/wp-content/uploads/2016/02/032_main.jpg
#
# Image.create(name1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS35ETh4RMDxYIwI4m9QYRi5NwJXLbx5HY5ljZ_uKGdw2AXjxeQrA', name2: 'NIKE_t.png', name2: 'NIKE_t.png', name3: 'NIKE_t.png',)
# Image.create(name1: 'https://pbs.twimg.com/media/Bfz3R0pIQAAIMBA.jpg', name2: 'bear.jpg', name2: 'bear.jpg', name3: 'bear.jpg',)
# Image.create(name1: 'https://static.clubt.jp/image/product/S0000034836/4991835.jpg', name2: 'bear.jpg', name2: 'bear.jpg', name3: 'bear.jpg',)
# Image.create(name1: 'https://www.biteki.com/wp-content/uploads/2016/12/2016bc_reader_304.jpg', name2: 'bear.jpg', name2: 'bear.jpg', name3: 'bear.jpg',)

# Product.create(name: 'かっこいいナイキのTシャツ', description: '超かっこいい！！！', price: '1200', status: '良い', brand: 'nike', user_id: 1)
# Product.create(name: '宇多田ヒカルのくま「ぼくはくま　くま　くま　くま〜」', description: '超かっこいい！！！',price: '33333', status: '良い', brand: 'hikaru', user_id: 2)
# Product.create(name: 'アンパンマンTシャツ', description: 'すげえいかす！！！！', price: '500')
